---
- name: install puma service file
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/{{ site_app_user }}.service
  notify:
    - restart puma app
  become: yes

- name: enable puma service
  systemd:
    name: "{{ site_app_user }}"
    enabled: yes
  become: yes
