---
- name: create app user
  user:
    name: "{{ site_app_user }}"
    home: "{{ site_deployment_path }}"
    createhome: no
    state: present
  become: yes

- name: add group of app_user to groups of www-data
  user:
    name: www-data
    groups: "{{ site_app_group }}"
    append: yes
  notify:
    - restart nginx
  become: yes

- name: clone project
  git:
    repo: "{{ site_repo_url }}"
    dest: "{{ site_deployment_path }}"
    accept_hostkey: yes

- name: set the app user as the owner
  file:
    path: "{{ site_deployment_path }}"
    owner: "{{ site_app_user }}"
    group: "{{ site_app_group }}"
    recurse: yes
    state: directory
  become: yes
