---
- name: install packages needed by Ansible for postgres
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-dev
    - python-psycopg2
  become: yes

- name: add postgres server key
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present
  become: yes

- name: add postgres repo
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
    state: present
    update_cache: yes
  become: yes

- name: install postgres
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-{{ postgres_version }}
    - postgresql-server-dev-{{ postgres_version }}
  become: yes

- name: create database role
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    role_attr_flags: SUPERUSER
    state: present
  become: yes
  become_user: postgres

- name: create database
  postgresql_db:
    db: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
    state: present
  become: yes
  become_user: postgres
