common: &common
  digest: voluntari.gov.ro

development:
  <<: *common
  mail_url_host: test-contribute.rusanu.com

test:
  <<: *common
  mail_url_host: www.example.com

production:
  <<: *common
  mail_url_host: voluntari.ithub.gov.ro
