common: &common
  digest: voluntari.gov.ro

development:
  <<: *common
  mail_url_host: localhost:3000

test:
  <<: *common
  mail_url_host: example.com

production:
  <<: *common
  mail_url_host: voluntari.gov.ro
