common: &common
  digest: voluntari.gov.ro

development:
  <<: *common
  mail_url_host: localhost.local

test:
  <<: *common
  mail_url_host: example.com

production:
  <<: *common
  mail_url_host: comunitate.code4.ro
