common: &common
  

development:
  <<: *common
  from: <%= ENV['VOLUNTARI_EMAIL_DEVELOPMENT_FROM'] %>
  to: <%= ENV['VOLUNTARI_EMAIL_DEVELOPMENT_TO'] %>
  daily_to: <%= ENV['VOLUNTARI_EMAIL_DEVELOPMENT_DAILY_TO'] %>
  
test:
  <<: *common
  from: someone@example.com
  daily_to: blackhole@example.com

production:
  from: <%= ENV['VOLUNTARI_EMAIL_PROD_FROM'] %>
  openings_contact: <%= ENV['VOLUNTARI_EMAIL_PROD_FROM'] %>
  daily_to: <%= ENV['VOLUNTARI_EMAIL_DAILY_TO'] %>
    

