# NB: This is an "on-disk" structure. These values exists in the database.
# You cannot change exiting values. If you must, a migration is required.

0:  
  status: Aprobat
  bgcolor: grey
  textcolor: white

1:
  status: Formare echipă
  bgcolor: green
  textcolor: white

2:
  status: Incubare
  bgcolor: yellow
  textcolor: black

3:
  status: UX/UI
  bgcolor: grey
  textcolor: black

4:
  status: Arhitectură
  bgcolor: green
  textcolor: white

5:
  status: Dezvoltare
  bgcolor: green
  textcolor: black

6:
  status: Testare
  bgcolor: orange
  textcolor: black

7:
  status: Lansare
  bgcolor: blue
  textcolor: black
