# This file defines the project Links 
# The YAML item record name is the hash key, so keep it as a correct symbol (smallcase, no spaces, no dashes)
github:
  label: GitHub
  helptext: Link la proiect in GitHub
  placeholder: https://github.com/code4romania/volunt-app

slack:
  label: Slack
  helptext: Link la canalul de Slack
  placeholder: https://code4romania.slack.com/messages/project_colabapp/

site:
  label: Site
  helptext: Link la proiectul live, daca e cazul
  placeholder: http://colab.code4.ro

