# This file defines the project Links 
# The YAML item record name is the hash key, so keep it as a correct symbol (smallcase, no spaces, no dashes)
github1:
  label: GitHub
  helptext: Link la repo în GitHub (de exemplu API)
  placeholder: https://github.com/code4romania/volunt-app

github2:
  label: GitHub
  helptext: Link la repo în GitHub (de exemplu client)
  placeholder: https://github.com/code4romania/volunt-app

slack:
  label: Slack
  helptext: Link la canalul de Slack
  placeholder: https://code4romania.slack.com/messages/project_colabapp/

site:
  label: Site
  helptext: Link la proiectul live, dacă e cazul
  placeholder: http://comunitate.code4.ro

